### ISSUE TITLE
Cannot get this to run no matter what

### ISSUE THREAD

**Issue by optikalefx** [patience-tema-baron/ember-keyboard#72]
I feel like I must be missing something, but I've read everything I can so far.

- I've got the addon installed, ember restarted.
- in my app route (this will be a global shortcut) I have `import { EKMixin } from 'ember-keyboard';`
- In my app controller, I have `import { keyUp, keyDown } from 'ember-keyboard';` and `this.set('keyboardActivated', true);` on the init method.
- In my app route, I have `export default Route.extend(EKMixin, {`
- Then I `import { on } from "@ember/object/evented"`
- Finally I have `aFunction: on(keyUp('KeyS'), function() {`
And it never fires.

I thought, maybe you can't do this in a controller. So I repeated the same steps in a component, setting `keyboardActivated` on init of the component, using `Ember.on` as opposed to just `on` via the modules syntax. Just not sure what is missing here.

**Comment by optikalefx** [comment]
Ember 2.15.0 by the way

**Comment by buschtoens** [comment]
You have to use the mixin in the same object that you set `keyboardActivated` and add the event handler, e.g. everything on your application route.

**Comment by optikalefx** [comment]
Thanks for getting back to me.

In my app route I have

```
import { EKMixin } from 'ember-keyboard';

export default Route.extend(EKMixin, {
	init() {
		this._super(...arguments);
		this.set('keyboardActivated', true);
	},
```

And then in my app controller I have

```
import { keyUp, keyDown } from 'ember-keyboard';
import { on } from "@ember/object/evented"

export default Controller.extend({
	aFunction: on(keyUp('KeyS'), function() {
		console.log('key s');
	}),
```

But still nothing logging at this point.

**Comment by patience-tema-baron** [comment]
Have you tried:

```js
import { EKMixin } from 'ember-keyboard';
import { keyUp, keyDown } from 'ember-keyboard';
import { on } from "@ember/object/evented"

export default Controller.extend(EKMixin, {
	init() {
		this._super(...arguments);
		this.set('keyboardActivated', true);
	},
	aFunction: on(keyUp('KeyS'), function() {
		console.log('key s');
	}),
```

**Comment by optikalefx** [comment]
That did it. Awesome. Thanks!
