### ISSUE TITLE
Upgrading to 3.0.0 - no change log?

### ISSUE THREAD

**Issue by xtagon** [patience-tema-baron/ember-keyboard#81]
Hi,

My app currently uses 2.3.0 and I noticed 3.0.0 is available, but I cannot find a CHANGELOG or HISTORY or NEWS file. Is there such a changelog? Is there any documentation on major changes or backwards compatible changes required for a major version update?

Thanks

**Comment by patience-tema-baron** [comment]
Hi! You might be looking for [this](https://github.com/patience-tema-baron/ember-keyboard/releases). Odds are, you'll be safe to upgrade.

**Comment by xtagon** [comment]
That's just what I was looking for - sorry I didn't think to check the releases. Thank you! 👍
